[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Extends cargo to query crates.io registry for crates details"
homepage = "https://gitlab.com/imp/cargo-info"
keywords = ["cargo", "info", "subcommand"]
license = "Apache-2.0/MIT"
name = "cargo-info"
repository = "https://gitlab.com/imp/cargo-info.git"
version = "0.4.3"

[dependencies]
chrono = "0.2"
chrono-humanize = "0.0.6"
json = "0.10"
pager = "0.2.2"
requests = "0.0.22"

[dependencies.clap]
features = ["unstable"]
version = "2"

[features]
default = []
