[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Extends cargo to query remote registry for crates details"
homepage = "https://gitlab.com/imp/cargo-info"
keywords = ["cargo", "info", "subcommand"]
license = "Apache-2.0/MIT"
name = "cargo-info"
repository = "https://gitlab.com/imp/cargo-info.git"
version = "0.1.0"

[dependencies]
clap = "2.4.0"
