[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Extends cargo to query crates.io registry for crates details"
homepage = "https://gitlab.com/imp/cargo-info"
keywords = ["cargo", "info", "subcommand"]
license = "Apache-2.0/MIT"
name = "cargo-info"
repository = "https://gitlab.com/imp/cargo-info.git"
version = "0.3.0"

[dependencies]
requests = "0.0.*"
json = "0.4"

[dependencies.clap]
version = "2"
features = ["unstable"]

[features]
default = []
