[package]
name = "nvimsplit"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
color-eyre = "0.6.2"
log = "0.4.14"
neovim-lib = "0.6.1"
simplelog = "0.9.0"
