  # Point size
  size: 7.5

  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    family: Source Code Pro
    #family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    #style: Regular
