  # Point size
  size: 11.0

  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    #family: Source Code Pro
    family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    #style: Regular
