name: hsutils
version: 0.0.0
synopsis: Small utilities written in Haskell
dependencies:
  - aeson
  - base >= 4.16 && <5
  - base64
  - bytestring
  - containers
  - directory
  - generic-lens
  - http-client
  - http-client-tls
  - http-types
  - microlens
  - optparse-applicative
  - megaparsec
  - perfetto-proto
  - proto-lens
  - raw-strings-qq
  - rio
  - text
  - time
  - vector
  - yaml

library:
  source-dirs: src

executables:
  nix-prefetch-github2:
    main: NixPrefetchGitHub.Main
    source-dirs: app
    dependencies:
      - hsutils
  journal2perfetto:
    main: JournaldToPerfetto.Main
    source-dirs: app
    dependencies:
      - hsutils
  # intercept2perfetto:
  #   main: Intercept2Perfetto.Main
  #   source-dirs: app
  #   dependencies:
  #     - hsutils

tests:
  test:
    main: Spec
    source-dirs: test
    dependencies:
      - hsutils
      - hspec
      - hspec-core
      - hspec-golden
      - pretty-simple
    build-tools: hspec-discover

    ghc-options:
      # people write bad pattern matches in tests lol
      - -Wno-incomplete-uni-patterns

ghc-options:
  - -Wall
  - -Wno-type-defaults
  - -Wno-name-shadowing
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - ImpredicativeTypes
  - InstanceSigs
  - LambdaCase
  - LexicalNegation
  - MonoLocalBinds
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
