name: hsutils
version: 0.0.0
synopsis: Small utilities written in Haskell
dependencies:
  - aeson
  - base >= 4.9 && <5
  - bytestring
  - directory
  - generic-lens
  - http-client
  - http-client-tls
  - http-types
  - microlens
  - optparse-applicative
  - raw-strings-qq
  - rio
  - yaml

library:
  source-dirs: src

executables:
  nix-prefetch-github:
    main: NixPrefetchGitHub.Main
    source-dirs: app
    dependencies:
      - hsutils

ghc-options:
  - -Wall
  - -Wno-type-defaults
  - -Wno-name-shadowing
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - ImpredicativeTypes
  - InstanceSigs
  - LambdaCase
  - LexicalNegation
  - MonoLocalBinds
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
